// База игр для демонстрации. Требования — ориентировочные, основаны на
// открытых системных требованиях игр и упрощены до единой шкалы 1..100
// (см. lib/hardware.js), чтобы алгоритм совместимости мог их сравнивать.
// Это НЕ официальные данные производителей и НЕ точный бенчмарк.

export const GENRES = [
  "Экшен",
  "Шутер",
  "RPG",
  "Гонки",
  "Симулятор",
  "Песочница",
  "Battle Royale",
  "MOBA",
  "Хоррор",
  "Аркада",
  "Головоломка",
  "Спорт",
];

export const GAMES = [
  {
    slug: "minecraft",
    title: "Minecraft",
    developer: "Mojang Studios",
    genres: ["Песочница", "Экшен"],
    image: "⛏️",
    color: "#5a8f3c",
    sizeGb: 1,
    popularity: 99,
    free: false,
    platforms: ["Steam-независимо", "Microsoft Store"],
    tags: ["multiplayer", "singleplayer", "4gb", "weak-pc"],
    description:
      "Песочница с открытым миром, где можно строить и исследовать. Один из самых нетребовательных проектов в списке — идеален для слабых ПК.",
    min: { cpu: 5, gpu: 3, ram: 4, vram: 1, os: "Windows 10", directx: "11" },
    rec: { cpu: 12, gpu: 8, ram: 8, vram: 2, os: "Windows 10/11", directx: "12" },
  },
  {
    slug: "roblox",
    title: "Roblox",
    developer: "Roblox Corporation",
    genres: ["Песочница", "Аркада"],
    image: "🧱",
    color: "#e2e2e2",
    sizeGb: 1,
    popularity: 97,
    free: true,
    platforms: ["Официальный лаунчер"],
    tags: ["multiplayer", "4gb", "weak-pc"],
    description:
      "Платформа с миллионами пользовательских игр. Требования зависят от конкретной игры, но базовый клиент очень лёгкий.",
    min: { cpu: 5, gpu: 3, ram: 4, vram: 1, os: "Windows 10", directx: "10" },
    rec: { cpu: 12, gpu: 8, ram: 8, vram: 2, os: "Windows 10/11", directx: "11" },
  },
  {
    slug: "fortnite",
    title: "Fortnite",
    developer: "Epic Games",
    genres: ["Battle Royale", "Шутер"],
    image: "🪂",
    color: "#7c5cff",
    sizeGb: 30,
    popularity: 95,
    free: true,
    platforms: ["Epic Games"],
    tags: ["multiplayer", "8gb"],
    description:
      "Популярный battle royale с частыми обновлениями графики. Требует Epic Games Launcher.",
    min: { cpu: 14, gpu: 8, ram: 8, vram: 2, os: "Windows 10", directx: "11" },
    rec: { cpu: 27, gpu: 19, ram: 16, vram: 6, os: "Windows 10/11", directx: "12" },
  },
  {
    slug: "gta-v",
    title: "GTA V",
    developer: "Rockstar Games",
    genres: ["Экшен", "Гонки"],
    image: "🚗",
    color: "#4caf50",
    sizeGb: 95,
    popularity: 96,
    free: false,
    platforms: ["Steam", "Epic Games", "Rockstar Games"],
    tags: ["singleplayer", "multiplayer", "8gb"],
    description:
      "Открытый мир Лос-Сантоса. Хорошо масштабируется по настройкам графики — идёт даже на скромном железе на низких.",
    min: { cpu: 14, gpu: 11, ram: 4, vram: 1, os: "Windows 10", directx: "10" },
    rec: { cpu: 25, gpu: 19, ram: 8, vram: 4, os: "Windows 10/11", directx: "11" },
  },
  {
    slug: "gta-vi",
    title: "GTA VI",
    developer: "Rockstar Games",
    genres: ["Экшен", "Гонки"],
    image: "🌴",
    color: "#ff6b81",
    sizeGb: 150,
    popularity: 98,
    free: false,
    platforms: ["ожидается: Steam / Rockstar Games"],
    tags: ["singleplayer", "multiplayer"],
    description:
      "Официальные системные требования для ПК ещё не опубликованы Rockstar. Требования ниже — приблизительная оценка по аналогии с современными играми на новых движках.",
    min: { cpu: 40, gpu: 33, ram: 16, vram: 8, os: "Windows 11", directx: "12" },
    rec: { cpu: 58, gpu: 50, ram: 32, vram: 12, os: "Windows 11", directx: "12" },
    estimated: true,
  },
  {
    slug: "cs2",
    title: "Counter-Strike 2",
    developer: "Valve",
    genres: ["Шутер"],
    image: "🔫",
    color: "#f4a825",
    sizeGb: 45,
    popularity: 94,
    free: true,
    platforms: ["Steam"],
    tags: ["multiplayer", "8gb"],
    description:
      "Киберспортивный шутер на движке Source 2. Хорошо оптимизирован, но требователен к процессору для высокого FPS.",
    min: { cpu: 14, gpu: 11, ram: 8, vram: 2, os: "Windows 10", directx: "11" },
    rec: { cpu: 27, gpu: 19, ram: 8, vram: 4, os: "Windows 10/11", directx: "12" },
  },
  {
    slug: "valorant",
    title: "Valorant",
    developer: "Riot Games",
    genres: ["Шутер"],
    image: "🎯",
    color: "#ff4655",
    sizeGb: 30,
    popularity: 92,
    free: true,
    platforms: ["Riot Client"],
    tags: ["multiplayer", "4gb", "weak-pc"],
    description:
      "Тактический шутер, специально оптимизированный под слабое и среднее железо.",
    min: { cpu: 8, gpu: 6, ram: 4, vram: 1, os: "Windows 10", directx: "11" },
    rec: { cpu: 18, gpu: 13, ram: 8, vram: 2, os: "Windows 10/11", directx: "11" },
  },
  {
    slug: "pubg",
    title: "PUBG: Battlegrounds",
    developer: "Krafton",
    genres: ["Battle Royale", "Шутер"],
    image: "🪖",
    color: "#c9a24b",
    sizeGb: 35,
    popularity: 85,
    free: true,
    platforms: ["Steam"],
    tags: ["multiplayer", "8gb"],
    description: "Один из первых массовых battle royale, требователен к процессору.",
    min: { cpu: 17, gpu: 13, ram: 8, vram: 2, os: "Windows 10", directx: "11" },
    rec: { cpu: 32, gpu: 24, ram: 16, vram: 6, os: "Windows 10/11", directx: "12" },
  },
  {
    slug: "apex-legends",
    title: "Apex Legends",
    developer: "Respawn Entertainment",
    genres: ["Battle Royale", "Шутер"],
    image: "⚡",
    color: "#da2b2b",
    sizeGb: 60,
    popularity: 90,
    free: true,
    platforms: ["Steam", "EA App"],
    tags: ["multiplayer", "8gb"],
    description: "Динамичный battle royale на движке Source, требует стабильный FPS для комфортной игры.",
    min: { cpu: 14, gpu: 13, ram: 6, vram: 2, os: "Windows 10", directx: "11" },
    rec: { cpu: 27, gpu: 24, ram: 8, vram: 6, os: "Windows 10/11", directx: "12" },
  },
  {
    slug: "terraria",
    title: "Terraria",
    developer: "Re-Logic",
    genres: ["Песочница", "Аркада"],
    image: "⛏️",
    color: "#8fd3f4",
    sizeGb: 1,
    popularity: 88,
    free: false,
    platforms: ["Steam"],
    tags: ["multiplayer", "singleplayer", "4gb", "weak-pc"],
    description: "2D песочница, запускается почти на любом ПК, включая очень старые.",
    min: { cpu: 5, gpu: 3, ram: 4, vram: 1, os: "Windows 7", directx: "9" },
    rec: { cpu: 8, gpu: 6, ram: 4, vram: 1, os: "Windows 10/11", directx: "11" },
  },
  {
    slug: "euro-truck-simulator-2",
    title: "Euro Truck Simulator 2",
    developer: "SCS Software",
    genres: ["Симулятор"],
    image: "🚛",
    color: "#2c7be5",
    sizeGb: 10,
    popularity: 80,
    free: false,
    platforms: ["Steam"],
    tags: ["singleplayer", "multiplayer", "4gb", "weak-pc"],
    description: "Спокойный симулятор дальнобойщика, отлично идёт на слабых и средних ПК.",
    min: { cpu: 8, gpu: 6, ram: 4, vram: 1, os: "Windows 10", directx: "10" },
    rec: { cpu: 17, gpu: 13, ram: 6, vram: 2, os: "Windows 10/11", directx: "11" },
  },
  {
    slug: "beamng-drive",
    title: "BeamNG.drive",
    developer: "BeamNG GmbH",
    genres: ["Симулятор", "Гонки"],
    image: "💥",
    color: "#e07b39",
    sizeGb: 25,
    popularity: 70,
    free: false,
    platforms: ["Steam"],
    tags: ["singleplayer", "8gb"],
    description: "Продвинутая физика разрушений автомобилей, сильно нагружает процессор.",
    min: { cpu: 17, gpu: 13, ram: 8, vram: 2, os: "Windows 10", directx: "11" },
    rec: { cpu: 34, gpu: 27, ram: 16, vram: 6, os: "Windows 10/11", directx: "11" },
  },
  {
    slug: "forza-horizon-5",
    title: "Forza Horizon 5",
    developer: "Playground Games",
    genres: ["Гонки"],
    image: "🏎️",
    color: "#ff9800",
    sizeGb: 110,
    popularity: 89,
    free: false,
    platforms: ["Steam", "Microsoft Store"],
    tags: ["singleplayer", "multiplayer", "16gb"],
    description: "Открытый мир с фотореалистичной графикой, требует современную видеокарту для высоких настроек.",
    min: { cpu: 17, gpu: 17, ram: 8, vram: 2, os: "Windows 10", directx: "12" },
    rec: { cpu: 34, gpu: 40, ram: 16, vram: 8, os: "Windows 10/11", directx: "12" },
  },
  {
    slug: "elden-ring",
    title: "Elden Ring",
    developer: "FromSoftware",
    genres: ["RPG", "Экшен"],
    image: "⚔️",
    color: "#c9a24b",
    sizeGb: 60,
    popularity: 93,
    free: false,
    platforms: ["Steam"],
    tags: ["singleplayer", "multiplayer", "8gb"],
    description: "Требовательная RPG с открытым миром, рекомендуется видеокарта уровня GTX 1060 и выше.",
    min: { cpu: 17, gpu: 19, ram: 12, vram: 4, os: "Windows 10", directx: "12" },
    rec: { cpu: 34, gpu: 33, ram: 16, vram: 8, os: "Windows 10/11", directx: "12" },
  },
  {
    slug: "cyberpunk-2077",
    title: "Cyberpunk 2077",
    developer: "CD Projekt Red",
    genres: ["RPG", "Шутер"],
    image: "🌆",
    color: "#f7e017",
    sizeGb: 70,
    popularity: 91,
    free: false,
    platforms: ["Steam", "GOG", "Epic Games"],
    tags: ["singleplayer", "16gb"],
    description: "Одна из самых требовательных игр в списке, особенно с трассировкой лучей.",
    min: { cpu: 17, gpu: 19, ram: 8, vram: 4, os: "Windows 10", directx: "12" },
    rec: { cpu: 44, gpu: 46, ram: 16, vram: 8, os: "Windows 10/11", directx: "12" },
  },
  {
    slug: "red-dead-redemption-2",
    title: "Red Dead Redemption 2",
    developer: "Rockstar Games",
    genres: ["Экшен", "RPG"],
    image: "🤠",
    color: "#b5651d",
    sizeGb: 150,
    popularity: 90,
    free: false,
    platforms: ["Steam", "Epic Games", "Rockstar Games"],
    tags: ["singleplayer", "16gb"],
    description: "Огромный открытый мир с отличной оптимизацией под разное железо, но требует много места на диске.",
    min: { cpu: 17, gpu: 17, ram: 8, vram: 4, os: "Windows 10", directx: "12" },
    rec: { cpu: 34, gpu: 33, ram: 12, vram: 8, os: "Windows 10/11", directx: "12" },
  },
  {
    slug: "the-witcher-3",
    title: "The Witcher 3: Wild Hunt",
    developer: "CD Projekt Red",
    genres: ["RPG"],
    image: "🐺",
    color: "#d9534f",
    sizeGb: 50,
    popularity: 92,
    free: false,
    platforms: ["Steam", "GOG", "Epic Games"],
    tags: ["singleplayer", "8gb"],
    description: "Классическая RPG с открытым миром, хорошо масштабируется под средние ПК.",
    min: { cpu: 14, gpu: 11, ram: 6, vram: 2, os: "Windows 7", directx: "11" },
    rec: { cpu: 27, gpu: 24, ram: 8, vram: 6, os: "Windows 10/11", directx: "11" },
  },
  {
    slug: "portal-2",
    title: "Portal 2",
    developer: "Valve",
    genres: ["Головоломка", "Экшен"],
    image: "🌀",
    color: "#ff7f27",
    sizeGb: 10,
    popularity: 87,
    free: false,
    platforms: ["Steam"],
    tags: ["singleplayer", "multiplayer", "4gb", "weak-pc"],
    description: "Легендарная головоломка на движке Source, запускается почти на любом ПК.",
    min: { cpu: 8, gpu: 6, ram: 2, vram: 1, os: "Windows 7", directx: "9" },
    rec: { cpu: 12, gpu: 8, ram: 4, vram: 1, os: "Windows 10/11", directx: "11" },
  },
  {
    slug: "left-4-dead-2",
    title: "Left 4 Dead 2",
    developer: "Valve",
    genres: ["Шутер", "Хоррор"],
    image: "🧟",
    color: "#7a1f1f",
    sizeGb: 15,
    popularity: 82,
    free: false,
    platforms: ["Steam"],
    tags: ["multiplayer", "4gb", "weak-pc"],
    description: "Кооперативный зомби-шутер, очень старый и лёгкий движок Source.",
    min: { cpu: 5, gpu: 3, ram: 2, vram: 1, os: "Windows 7", directx: "9" },
    rec: { cpu: 12, gpu: 8, ram: 4, vram: 1, os: "Windows 10/11", directx: "9" },
  },
  {
    slug: "among-us",
    title: "Among Us",
    developer: "Innersloth",
    genres: ["Аркада"],
    image: "🚀",
    color: "#c51111",
    sizeGb: 1,
    popularity: 84,
    free: false,
    platforms: ["Steam"],
    tags: ["multiplayer", "4gb", "weak-pc"],
    description: "Очень лёгкая социальная игра, запустится даже на офисном ноутбуке.",
    min: { cpu: 5, gpu: 3, ram: 2, vram: 1, os: "Windows 7", directx: "10" },
    rec: { cpu: 8, gpu: 3, ram: 4, vram: 1, os: "Windows 10/11", directx: "11" },
  },
  {
    slug: "rocket-league",
    title: "Rocket League",
    developer: "Psyonix",
    genres: ["Спорт", "Аркада"],
    image: "🚙",
    color: "#1fa2ff",
    sizeGb: 20,
    popularity: 86,
    free: true,
    platforms: ["Steam", "Epic Games"],
    tags: ["multiplayer", "4gb", "weak-pc"],
    description: "Футбол на машинах — быстрый геймплей при невысоких требованиях.",
    min: { cpu: 8, gpu: 6, ram: 4, vram: 1, os: "Windows 10", directx: "11" },
    rec: { cpu: 17, gpu: 13, ram: 8, vram: 2, os: "Windows 10/11", directx: "11" },
  },
  {
    slug: "warframe",
    title: "Warframe",
    developer: "Digital Extremes",
    genres: ["Экшен", "RPG"],
    image: "🛡️",
    color: "#3fa7d6",
    sizeGb: 45,
    popularity: 78,
    free: true,
    platforms: ["Steam"],
    tags: ["multiplayer", "8gb"],
    description: "Free-to-play кооперативный экшен с гибкими настройками графики.",
    min: { cpu: 8, gpu: 8, ram: 4, vram: 1, os: "Windows 10", directx: "11" },
    rec: { cpu: 22, gpu: 19, ram: 8, vram: 4, os: "Windows 10/11", directx: "12" },
  },
  {
    slug: "dota-2",
    title: "Dota 2",
    developer: "Valve",
    genres: ["MOBA"],
    image: "🛡️",
    color: "#b71c1c",
    sizeGb: 40,
    popularity: 89,
    free: true,
    platforms: ["Steam"],
    tags: ["multiplayer", "4gb", "weak-pc"],
    description: "Популярная MOBA, хорошо оптимизирована даже под слабые видеокарты.",
    min: { cpu: 8, gpu: 6, ram: 4, vram: 1, os: "Windows 7", directx: "11" },
    rec: { cpu: 18, gpu: 13, ram: 8, vram: 2, os: "Windows 10/11", directx: "11" },
  },
  {
    slug: "league-of-legends",
    title: "League of Legends",
    developer: "Riot Games",
    genres: ["MOBA"],
    image: "🏆",
    color: "#0ac8b9",
    sizeGb: 20,
    popularity: 93,
    free: true,
    platforms: ["Riot Client"],
    tags: ["multiplayer", "4gb", "weak-pc"],
    description: "Одна из самых нетребовательных MOBA, идёт почти на любом ПК.",
    min: { cpu: 5, gpu: 3, ram: 2, vram: 1, os: "Windows 7", directx: "9" },
    rec: { cpu: 12, gpu: 8, ram: 4, vram: 1, os: "Windows 10/11", directx: "11" },
  },
  {
    slug: "overwatch-2",
    title: "Overwatch 2",
    developer: "Blizzard Entertainment",
    genres: ["Шутер"],
    image: "🦾",
    color: "#f99e1a",
    sizeGb: 30,
    popularity: 85,
    free: true,
    platforms: ["Battle.net"],
    tags: ["multiplayer", "4gb", "weak-pc"],
    description: "Командный шутер с яркой стилизованной графикой и невысокими требованиями.",
    min: { cpu: 8, gpu: 8, ram: 4, vram: 1, os: "Windows 10", directx: "11" },
    rec: { cpu: 18, gpu: 17, ram: 8, vram: 4, os: "Windows 10/11", directx: "11" },
  },
  {
    slug: "genshin-impact",
    title: "Genshin Impact",
    developer: "HoYoverse",
    genres: ["RPG", "Экшен"],
    image: "⛩️",
    color: "#8ec6ff",
    sizeGb: 100,
    popularity: 88,
    free: true,
    platforms: ["Официальный лаунчер"],
    tags: ["singleplayer", "multiplayer", "8gb"],
    description: "Аниме-RPG с открытым миром, требует SSD и стабильный интернет для загрузок.",
    min: { cpu: 8, gpu: 8, ram: 8, vram: 2, os: "Windows 7", directx: "11" },
    rec: { cpu: 22, gpu: 19, ram: 16, vram: 6, os: "Windows 10/11", directx: "11" },
  },
  {
    slug: "fall-guys",
    title: "Fall Guys",
    developer: "Mediatonic",
    genres: ["Аркада", "Battle Royale"],
    image: "🫘",
    color: "#ffb6c1",
    sizeGb: 8,
    popularity: 75,
    free: true,
    platforms: ["Steam", "Epic Games"],
    tags: ["multiplayer", "4gb", "weak-pc"],
    description: "Весёлый мультиплеерный платформер с мультяшной графикой и низкими требованиями.",
    min: { cpu: 8, gpu: 6, ram: 4, vram: 1, os: "Windows 10", directx: "11" },
    rec: { cpu: 14, gpu: 11, ram: 8, vram: 2, os: "Windows 10/11", directx: "11" },
  },
  {
    slug: "phasmophobia",
    title: "Phasmophobia",
    developer: "Kinetic Games",
    genres: ["Хоррор"],
    image: "👻",
    color: "#6a0dad",
    sizeGb: 15,
    popularity: 79,
    free: false,
    platforms: ["Steam"],
    tags: ["multiplayer", "8gb"],
    description: "Кооперативный хоррор про охоту за призраками, требует VR-совместимое железо для VR-режима (опционально).",
    min: { cpu: 14, gpu: 13, ram: 8, vram: 2, os: "Windows 10", directx: "11" },
    rec: { cpu: 22, gpu: 19, ram: 16, vram: 4, os: "Windows 10/11", directx: "12" },
  },
  {
    slug: "geometry-dash",
    title: "Geometry Dash",
    developer: "RobTop Games",
    genres: ["Аркада"],
    image: "🔺",
    color: "#00e5ff",
    sizeGb: 1,
    popularity: 81,
    free: false,
    platforms: ["Steam"],
    tags: ["singleplayer", "4gb", "weak-pc"],
    description: "Ритм-платформер, минимальные требования — почти любой современный ПК подойдёт.",
    min: { cpu: 5, gpu: 3, ram: 2, vram: 1, os: "Windows 7", directx: "9" },
    rec: { cpu: 8, gpu: 3, ram: 4, vram: 1, os: "Windows 10/11", directx: "10" },
  },
  {
    slug: "osu",
    title: "osu!",
    developer: "ppy Pty Ltd",
    genres: ["Аркада", "Спорт"],
    image: "🎵",
    color: "#ff66aa",
    sizeGb: 2,
    popularity: 83,
    free: true,
    platforms: ["Официальный сайт"],
    tags: ["multiplayer", "singleplayer", "4gb", "weak-pc"],
    description: "Ритм-игра, чувствительная к стабильному FPS и низкому input-lag, но сама по себе очень лёгкая.",
    min: { cpu: 5, gpu: 3, ram: 2, vram: 1, os: "Windows 7", directx: "9" },
    rec: { cpu: 14, gpu: 8, ram: 4, vram: 1, os: "Windows 10/11", directx: "11" },
  },
];

export function getGameBySlug(slug) {
  return GAMES.find((g) => g.slug === slug) || null;
}

export function getAllSlugs() {
  return GAMES.map((g) => g.slug);
}
